container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree lshw
  test_script:
#    - aria2c --bt-seed-unverified=true --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/venu952/download/009754/onejav.com_venu952.torrent"
    - "aria2c --check-certificate=false http://103.126.226.135:8080/download/TeenFidelity.E430.Gabbie.Carter.XXX.SD.MP4-KLEENEX/TeenFidelity.E430.Gabbie.Carter.XXX.SD.MP4-KLEENEX.mp4"
    - ffmpeg -i "TeenFidelity.E430.Gabbie.Carter.XXX.SD.MP4-KLEENEX.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Gabbie Carter" -preset veryfast TeenFidelity.E430.Gabbie.Carter.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "TeenFidelity.E430.Gabbie.Carter.x265.mp4"
